### ISSUE TITLE
dislike_count

### ISSUE THREAD

**Issue by ifuchs** [media-proxy/fs.youtube#52]
I have tried with several video_ids and I get:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ihf/opt/anaconda3/lib/python3.7/site-packages/fs/opener/registry.py", line 225, in open_fs
    default_protocol=default_protocol,
  File "/Users/ihf/opt/anaconda3/lib/python3.7/site-packages/fs/opener/registry.py", line 177, in open
    open_fs = opener.open_fs(fs_url, parse_result, writeable, create, cwd)
  File "/Users/ihf/opt/anaconda3/lib/python3.7/site-packages/fs/opener/youtubefs.py", line 44, in open_fs
    yt_fs = YoutubeFS(ytuuid, playlist=False)
  File "/Users/ihf/opt/anaconda3/lib/python3.7/site-packages/fs/youtube/youtubefs.py", line 125, in __init__
    self._title = pafy.new(self.url).title
  File "/Users/ihf/opt/anaconda3/lib/python3.7/site-packages/pafy/pafy.py", line 124, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts=ydl_opts)
  File "/Users/ihf/opt/anaconda3/lib/python3.7/site-packages/pafy/backend_youtube_dl.py", line 31, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/Users/ihf/opt/anaconda3/lib/python3.7/site-packages/pafy/backend_shared.py", line 97, in __init__
    self._fetch_basic()
  File "/Users/ihf/opt/anaconda3/lib/python3.7/site-packages/pafy/backend_youtube_dl.py", line 54, in _fetch_basic
    self._dislikes = self._ydl_info['dislike_count']
KeyError: 'dislike_count'`

**Comment by media-proxy** [comment]
Yes, youtube disabled the dislike information.

I'll check it out if I have time.
